version: '3.9'

volumes:
  pg:
  static:
  media:
  # frontend_build:

services:

  db:
    image: postgres:15
    container_name: db
    env_file: .env
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  backend:
    build: ./career_tracker_backend/ 
    env_file: .env
    restart: always
    # ports:
    #   - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - static:/backend_static
    #   - media:/backend_media
    depends_on:
      - db

  frontend:
    image: grimlerih/practicum
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  nginx:
    build: ./nginx/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80 