version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: career_tracker_backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: grimlerih/practicum:latest
    env_file: .env
    ports:
      - "5173:80"

  nginx:
    build: nginx/
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - media:/media/
      - static:/static
    depends_on:
      - backend
      