version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    # image: zalgan/career_tracker_backend
    build: career_tracker_backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    # ports:
    #   - "8000:8000"
    depends_on:
      - db

  frontend:
    image: grimlerih/practicum:latest
    env_file: .env
    ports:
      - "5173:80"

  nginx:
    # image: zalgan/career_tracker_nginx
    build: nginx/
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      # - ./frontend/build:/usr/share/nginx/html/
      - media:/media/
      - static:/static
    depends_on:
      - backend
      