version: '3.9'

volumes:
  pg_data:
  static:
  media:
  # frontend_build:

services:

  db:
    image: postgres:15
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./career_tracker_backend/ 
    env_file: .env
    restart: always
    # ports:
    #   - 8000:8000
    volumes:
      - static:/backend_static
      - media:/backend_media
    depends_on:
      - db

  frontend:
    image: grimlerih/practicum
    command:
      - cp -r www/html/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  nginx:
    build: ./nginx/
    volumes:
      - static:/staticfiles/
      - media:/var/html/media/
    ports:
      - 8000:80 