# Generated by Django 3.2 on 2023-12-02 00:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof_tests', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Пройденный процент теста')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof_tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Связь студента и теста',
                'verbose_name_plural': 'Связь студентов и тестов',
                'ordering': ('student',),
            },
        ),
        migrations.CreateModel(
            name='StudentSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_students', to='specialties.specialization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_specializations', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_payment', models.BooleanField(default=False, verbose_name='Статус покупки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_students', to='specialties.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Связь студента и курса',
                'verbose_name_plural': 'Связь студентов и курсов',
                'ordering': ('student',),
            },
        ),
        migrations.CreateModel(
            name='SprintStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_sprint', to='specialties.sprint', verbose_name='Спринт')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Связь студента и спринта',
                'verbose_name_plural': 'Связь студентов и спринтов',
                'ordering': ('student',),
            },
        ),
        migrations.CreateModel(
            name='SkillStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус получения навыка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_skill', to='specialties.skill', verbose_name='Навык')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Связь студента и навыка',
                'verbose_name_plural': 'Связь студентов и навыков',
                'ordering': ('student',),
            },
        ),
        migrations.AddConstraint(
            model_name='studenttest',
            constraint=models.UniqueConstraint(fields=('student', 'test'), name='unique_student_test'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course'),
        ),
    ]
