# Generated by Django 3.2 on 2023-11-26 14:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof_tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Пройденный процент теста')),
                ('result', models.BooleanField(default=False, verbose_name='Статус теста')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof_tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Связь студента и теста',
                'verbose_name_plural': 'Связь студентов и тестов',
                'ordering': ('student',),
            },
        ),
        migrations.AddConstraint(
            model_name='studenttest',
            constraint=models.UniqueConstraint(fields=('student', 'test'), name='unique_student_test'),
        ),
    ]
