# Generated by Django 3.2 on 2023-12-08 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0003_course_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_specialization', to='specialties.specialization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_specialization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
