# Generated by Django 3.2 on 2023-12-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialties', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_students', to='specialties.specialization', verbose_name='Специальность')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_specialization', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
    ]
