# Generated by Django 3.2 on 2023-12-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0004_remove_course_grade'),
        ('students', '0002_studentspecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentspecialization',
            name='current_grade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='students_specialization', to='specialties.grade'),
            preserve_default=False,
        ),
    ]
