# Generated by Django 3.2 on 2023-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default=1, max_length=200, verbose_name='Продолжительность курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='experience',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
