# Generated by Django 3.2 on 2023-12-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_alter_skill_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grades/'),
        ),
    ]
