# Generated by Django 3.2 on 2023-12-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_auto_20231208_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_grade', to='specialties.grade', verbose_name='Грейд'),
        ),
    ]
