# Generated by Django 3.2 on 2023-12-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0003_alter_grade_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='direction',
            field=models.ManyToManyField(related_name='specialties', to='specialties.Direction', verbose_name='Направление обучения'),
        ),
    ]
