# Generated by Django 3.2 on 2023-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0004_alter_specialization_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='image',
        ),
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specialties/'),
        ),
    ]
