# Generated by Django 3.2 on 2023-12-04 22:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0005_auto_20231203_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')], verbose_name='Цвет'),
        ),
    ]
