# Generated by Django 3.2 on 2023-12-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0006_direction_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='description',
        ),
        migrations.CreateModel(
            name='GradeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_direction', to='specialties.direction', verbose_name='Направление')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions_grade', to='specialties.grade', verbose_name='Грейд')),
            ],
            options={
                'verbose_name': 'Связь грейда и направления',
                'verbose_name_plural': 'Связи грейдов и направлений',
                'ordering': ('grade', 'direction'),
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='direction',
            field=models.ManyToManyField(through='specialties.GradeDirection', to='specialties.Direction', verbose_name='Направление'),
        ),
        migrations.AddConstraint(
            model_name='gradedirection',
            constraint=models.UniqueConstraint(fields=('grade', 'direction'), name='unique_grade_direction'),
        ),
    ]
